services:
  db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$(hostname -i)" ]
      interval: 3s
      timeout: 15s
      retries: 10
    volumes:
      - db:/var/lib/postgresql/18
    networks:
      common:
        aliases:
          - db

  pg-maintenance:
    build:
      context: ./
      dockerfile: Containerfile
    image: pg-maintenance
    environment:
      DB_USERNAME: "dev"
      DB_PASSWORD: "dev"
    command: [
      "/pg_maintenance",
      "--host", "${POSTGRES_HOST:-db}",
      "--port", "${POSTGRES_PORT:-5432}",
      "--db-name", "${POSTGRES_DB:-dev}",
      "--table", "dev:created_at:10",
      "--table", "dev2::10",
      "--batch", "100",
      "--timeout", "0s"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      common:
        aliases:
          - pg-maintenance

volumes:
  db:


networks:
  common:
    driver: bridge
